### ISSUE TITLE
Ligand atoms were not discarded prior to docking

### ISSUE THREAD

**Issue by rasbt** [HongjianLi/istar#1]
Dear Hongjian Li and developers,
I recently stumbled upon idock and found the approach really interesting and promising. I just tried out the idock/istar webserver a few days ago and must say that I am really impressed by the nice interface! 

However, I encountered one little issue. In the documentation at http://istar.cse.cuhk.edu.hk/idock/ it says:

> Submit your job. Only protein chains and ions will be sent to the server. Ligands and waters will be discarded.

Now, when I looked at the results, I saw that the ligand was not discarded. This is not a big problem since I could simply submit the job without ligand; I just thought it may be worth mentioning in the documentation. In my case, the ligand was simply listed as HETATM entries, maybe it requires some additional info in the PDB file to recognize it correctly? (I attached the input file below)

![screen shot 2016-06-16 at 2 04 31 pm](https://cloud.githubusercontent.com/assets/5618407/16127699/84e46482-33cb-11e6-858f-3e284d63c4f1.png)

[Struc_final80.pdb.zip](https://github.com/HongjianLi/istar/files/319051/Struc_final80.pdb.zip)

As a suggestion, maybe you could upload an example PDB file with ligand and ions so that a user can have a look which minimum format is required. 

In any case, thanks for the great tool!

**Comment by HongjianLi** [comment]
Hello Sebastian Raschka,
  The ligand was not recognized because it appears before the protein, which does not strictly conform to the official PDB specification. A simple solution is to move the ligand's HETATM lines to the end of the PDB file, i.e. after the protein's TER line. In this way the file looks more PDB conformant. I tried this and the server correctly recognized and discarded the ligand.

**Comment by rasbt** [comment]
Thanks for getting back on this issue, Jacky Lee, I appreciate it. This way you are parsing the files is actually pretty useful, it allows to keep certain ions and/or water molecules if desired but also allows to remove ligands if their HETATM entries are coming after the ATOM section. As a suggestion, it may be a good idea to add a short note or comment about that in the documentation?

**Comment by HongjianLi** [comment]
Hello Sebastian Raschka,
What you proposed is already in my to-do list. I also want to provide some buttons to allow users to select which chains/ligands/ions/cofactors to include to the receptor for docking. The biggest difficulty is that I currently don't have time to implement it, as I'm struggling with many other projects. I'm afraid this new functionality would not be possible until next year.

**Comment by rasbt** [comment]
Sounds awesome! I've seen some of your other projects, and I am truly impressed about the amount of good work there. I "accidentally" stumbled upon istar/idock when I was doing a literature search while writing on another paper. What I particularly like about it is the already great and convenient interface. Having used several other docking tools in the past, I must say that it is by far the most convenient & accessible out there. Thanks again for putting it together and even sharing the code on GitHub. You probably keep your todo list off-side, so please feel free to close this issue here on GitHub.

Cheers,
Sebastian
